using Microsoft.CodeAnalysis;
using vc.Ifx.Analyzers.Rules.CodeQuality;

namespace VisionaryCoder.Framework.Tests.Roslyn.Analyzers;

[TestClass]
public sealed class MethodNestingPolicyTests
{
    [TestMethod]
    [DataRow("if (true) { if (true) {} }", 2)]
    [DataRow("if (true) {} if (true) {}", 1)]
    [DataRow("if (true) {} else if (false) {}", 2)]
    [DataRow("for (;;) { while (true) { break; } break; }", 2)]
    [DataRow("do { foreach (int value in new int[0]) {} } while (false);", 2)]
    [DataRow("foreach (var (first, second) in new (int, int)[0]) { if (true) {} }", 2)]
    [DataRow("switch (1) { case 1: if (true) {} break; }", 2)]
    [DataRow("try { } catch { if (true) {} } finally { while (false) {} }", 2)]
    [DataRow("{ { if (true) {} } }", 1)]
    [DataRow("lock (this) { if (true) {} }", 1)]
    [DataRow("using (System.IDisposable value = null) { if (true) {} }", 1)]
    public async Task CountsControlStatementsAndNotSiblingOrPlainBlocks(string body, int expected)
    {
        string source = "class C { void Run() { " + body + " } }";
        var settings = new Dictionary<string, string> { ["dotnet_code_quality.IFX1100.max_nesting_depth"] = "0" };
        var diagnostics = await AnalyzerHarness.RunAsync(source, new MethodNestingAnalyzer(), settings);
        Assert.AreEqual(1, diagnostics.Length);
        Diagnostic diagnostic = diagnostics[0];
        Assert.AreEqual("IFX1100", diagnostic.Id);
        Assert.AreEqual("Run", source.Substring(diagnostic.Location.SourceSpan.Start, diagnostic.Location.SourceSpan.Length));
        Assert.AreEqual(DiagnosticSeverity.Warning, diagnostic.Severity);
        Assert.AreEqual($"Method 'Run' has control-flow nesting depth {expected} (maximum 0)", diagnostic.GetMessage());
        Assert.AreEqual("ControlFlowNestingDepth", diagnostic.Properties["MetricName"]);
        Assert.AreEqual("ifx-control-nesting-v1", diagnostic.Properties["MetricVersion"]);
        Assert.AreEqual(expected.ToString(System.Globalization.CultureInfo.InvariantCulture), diagnostic.Properties["MeasuredValue"]);
        Assert.AreEqual("0", diagnostic.Properties["Threshold"]);
        Assert.AreEqual("Maintainability", diagnostic.Descriptor.Category);
        StringAssert.EndsWith(diagnostic.Descriptor.HelpLinkUri, "#ifx1100");
    }

    [TestMethod]
    [DataRow(null, 4, 0)]
    [DataRow(null, 5, 1)]
    [DataRow("2", 2, 0)]
    [DataRow("2", 3, 1)]
    [DataRow("0", 0, 0)]
    [DataRow("0", 1, 1)]
    [DataRow("64", 5, 0)]
    [DataRow("65", 5, 1)]
    [DataRow("-1", 5, 1)]
    [DataRow("garbage", 5, 1)]
    [DataRow("999999999999999999999999", 5, 1)]
    public async Task ThresholdHasStableBoundaryAndInvalidFallback(string? configured, int depth, int expected)
    {
        var settings = new Dictionary<string, string>();
        if (configured is not null) settings["dotnet_code_quality.IFX1100.max_nesting_depth"] = configured;
        string source = "class C { void Run() { " + string.Concat(Enumerable.Repeat("if (true) { ", depth))
            + string.Concat(Enumerable.Repeat("}", depth)) + " } }";
        Assert.AreEqual(expected, (await AnalyzerHarness.RunAsync(source, new MethodNestingAnalyzer(), settings)).Length);
    }

    [TestMethod]
    public async Task NestedFunctionBodiesAndOtherMemberKindsAreOutsideScope()
    {
        const string source = """
            abstract class C
            {
                C() { if (true) { if (true) {} } }
                int Property { get { if (true) { if (true) {} } return 0; } }
                public abstract void Abstract();
                int Expression() => true ? 1 : 0;
                void Run()
                {
                    void Local() { if (true) { if (true) {} } }
                    System.Action first = () => { if (true) { if (true) {} } };
                    System.Action<int> second = x => { if (true) { if (true) {} } };
                    System.Action third = delegate { if (true) { if (true) {} } };
                }
            }
            """;
        Assert.AreEqual(0, (await AnalyzerHarness.RunAsync(source, new MethodNestingAnalyzer(),
            new() { ["dotnet_code_quality.IFX1100.max_nesting_depth"] = "0" })).Length);
    }

    [TestMethod]
    [DataRow("Policy.g.cs", "")]
    [DataRow("Policy.generated.cs", "")]
    [DataRow("Policy.cs", "// <auto-generated/>\n")]
    public async Task GeneratedMethodsAreExcluded(string path, string header)
    {
        string source = header + "class C { void Run() { if (true) {} } }";
        Assert.AreEqual(0, (await AnalyzerHarness.RunAsync(source, new MethodNestingAnalyzer(),
            new() { ["dotnet_code_quality.IFX1100.max_nesting_depth"] = "0" }, path)).Length);
    }
}
