using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using vc.Ifx.Generators;

namespace VisionaryCoder.Framework.Tests.Generators.Implementation;

[TestClass]
public sealed class MinimalEndpointGeneratorTests
{
    private const string Header = "using System; using System.Threading; using System.Threading.Tasks; using vc.Ifx.Generators.Abstractions.Attributes; ";

    [TestMethod]
    public void SimpleRegistryMatchesGoldenSourceAndCompiles()
    {
        var result = Run("internal static class Handlers { [GenerateEndpoint(\"/health\", \"get\")] internal static string Read() => \"healthy\"; }");
        result.AssertCompiles();
        result.Source.Should().Be("""
            // <auto-generated />
            #nullable enable
            namespace vc.Ifx.Generated;

            internal static class IfxEndpointRouteBuilderExtensions
            {
                public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapGeneratedIfxEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints)
                {
                    global::System.ArgumentNullException.ThrowIfNull(endpoints);
                    {
                        var endpoint = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, "/health", new string[] { "GET" }, (global::System.Delegate)global::Handlers.Read);
                    }
                    return endpoints;
                }
            }

            """.Replace("\r\n", "\n"));
    }

    [TestMethod]
    [DataRow("null", "\"GET\"")]
    [DataRow("\"\"", "\"GET\"")]
    [DataRow("\"relative\"", "\"GET\"")]
    [DataRow("\" /path\"", "\"GET\"")]
    [DataRow("\"/path \"", "\"GET\"")]
    [DataRow("\"/path\"", "null")]
    [DataRow("\"/path\"", "\" GET\"")]
    [DataRow("\"/path\"", "\"GET,POST\"")]
    [DataRow("\"/path\"", "\"CUSTOM\"")]
    [DataRow("\"/{broken\"", "\"GET\"")]
    [DataRow("\"/{\"", "\"GET\"")]
    [DataRow("\"/{*\"", "\"GET\"")]
    [DataRow("\"/{**\"", "\"GET\"")]
    [DataRow("\"/{*x\"", "\"GET\"")]
    [DataRow("\"/{***path}\"", "\"GET\"")]
    [DataRow("\"/{id}/{id}\"", "\"GET\"")]
    public void InvalidRouteOrMethodGetsDeclarationDiagnostic(string route, string method)
    {
        var result = Run($"internal static class H {{ [GenerateEndpoint({route}, {method})] internal static string Read() => \"ok\"; }}");
        AssertDiagnostic(result, "IFX2000");
        result.Source.Should().NotContain("global::H.Read");
    }

    [TestMethod]
    [DataRow("Name = \" \"")]
    [DataRow("Summary = \"\"")]
    [DataRow("Description = \" \"")]
    [DataRow("AuthorizationPolicy = \"\"")]
    [DataRow("Tags = null")]
    [DataRow("Tags = new string[] { null }")]
    [DataRow("Tags = new string[] { \" \" }")]
    public void InvalidNamedMetadataGetsDeclarationDiagnostic(string option) => AssertDiagnostic(Run(
        $"internal static class H {{ [GenerateEndpoint(\"/\", \"GET\", {option})] internal static string Read() => \"ok\"; }}"), "IFX2000");

    [TestMethod]
    [DataRow("public string Read() => \"ok\";")]
    [DataRow("private static string Read() => \"ok\";")]
    [DataRow("public static T Read<T>() => default!;")]
    [DataRow("public static void Read() { }")]
    [DataRow("public static Task Read() => Task.CompletedTask;")]
    [DataRow("public static ValueTask Read() => ValueTask.CompletedTask;")]
    [DataRow("public static Task<Task<string>> Read() => Task.FromResult(Task.FromResult(\"ok\"));")]
    [DataRow("public static string Read(ref int id) => id.ToString();")]
    [DataRow("public static string Read(in int id) => id.ToString();")]
    [DataRow("public static string Read(out int id) { id = 1; return \"ok\"; }")]
    [DataRow("public static ReadOnlySpan<char> Read() => \"ok\";")]
    [DataRow("public static unsafe int* Read() => null;")]
    [DataRow("public static unsafe delegate*<int> Read() => null;")]
    [DataRow("public static unsafe int*[] Read() => null!;")]
    [DataRow("public static ref int Read() => throw new Exception();")]
    [DataRow("public static ref readonly int Read() => throw new Exception();")]
    [DataRow("public static string Read() => \"ok\"; public static string Read(int x) => \"ok\";")]
    [DataRow("public static string Read(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j, int k, int l, int m, int n, int o, int p, int q) => \"ok\";")]
    public void UnsupportedSignaturesAreDiagnosed(string method) => AssertDiagnostic(Run(
        $"public class H {{ [GenerateEndpoint(\"/\", \"GET\")] {method} }}"), "IFX2001");

    [TestMethod]
    [DataRow("file static class H")]
    [DataRow("public static class H<T>")]
    [DataRow("public interface H")]
    public void UnsupportedContainersAreDiagnosed(string type) => AssertDiagnostic(Run(
        $"{type} {{ [GenerateEndpoint(\"/\", \"GET\")] public static string Read() => \"ok\"; }}"), "IFX2001");

    [TestMethod]
    public void PrivateNestedContainerIsDiagnosed() => AssertDiagnostic(Run(
        "public class Outer { private class H { [GenerateEndpoint(\"/\", \"GET\")] public static string Read() => \"ok\"; } }"), "IFX2001");

    [TestMethod]
    [DataRow("Task<string>", "Task.FromResult(\"ok\")")]
    [DataRow("ValueTask<string>", "ValueTask.FromResult(\"ok\")")]
    [DataRow("string[]", "new string[] { \"ok\" }")]
    [DataRow("int", "42")]
    [DataRow("TaskStatus", "TaskStatus.RanToCompletion")]
    [DataRow("Microsoft.AspNetCore.Http.IResult", "Microsoft.AspNetCore.Http.Results.Ok()")]
    public void SupportedReturnsCompile(string type, string body) => Run(
        $"internal static class H {{ [GenerateEndpoint(\"/\", \"GET\")] public static {type} Read() => {body}; }}").AssertCompiles();

    [TestMethod]
    public void DeclaredPayloadDelegateIsRejected() => AssertDiagnostic(Run(
        "internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static Func<int> Read() => () => 1; }"), "IFX2006");

    [TestMethod]
    public void UnboundDelegateParameterDiagnosticPointsToParameter()
    {
        var result = Run("internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static string Read(Func<int> action) => action().ToString(); }");
        var diagnostic = result.Diagnostics.Single(diagnostic => diagnostic.Id == "IFX2006");
        diagnostic.Location.SourceTree!.GetText().ToString(diagnostic.Location.SourceSpan).Should().Contain("action");
    }

    [TestMethod]
    public void ServiceDelegateAndCancellationBindingMetadataArePreserved()
    {
        var result = Run("internal static class H { [GenerateEndpoint(\"/{id}\", \"GET\")] public static string Read(int id, [Microsoft.AspNetCore.Mvc.FromServices] Func<string> value, CancellationToken cancellationToken) => value(); }");
        result.AssertCompiles();
        result.Source.Should().Contain("(global::System.Delegate)global::H.Read").And.NotContain("GetRequiredService");
    }

    [TestMethod]
    [DataRow("RequireAuthorization = true, AllowAnonymous = true", "")]
    [DataRow("AuthorizationPolicy = \"Read\", AllowAnonymous = true", "")]
    [DataRow("AllowAnonymous = true", "[Microsoft.AspNetCore.Authorization.Authorize]")]
    [DataRow("RequireAuthorization = true", "[Microsoft.AspNetCore.Authorization.AllowAnonymous]")]
    public void ConflictingAuthorizationIsDiagnosed(string options, string additionalAttribute) => AssertDiagnostic(Run(
        $"internal static class H {{ {additionalAttribute} [GenerateEndpoint(\"/\", \"GET\", {options})] public static string Read() => \"ok\"; }}"), "IFX2004");

    [TestMethod]
    public void AllMetadataEmitsInStableOrderAndCompiles()
    {
        var result = Run("internal static class H { [GenerateEndpoint(\"/\", \"PATCH\", Name=\"Edit\", Summary=\"Title\\nnext\", Description=\"Detail\", Tags=new string[]{\"One\",\"One\",\"Two\"}, RequireAuthorization=true, AuthorizationPolicy=\"Edit\", ExcludeFromDescription=true)] public static string Read() => \"ok\"; }");
        result.AssertCompiles();
        result.Source.Should().Contain("new string[] { \"One\", \"Two\" }");
        var calls = new[] { ".WithName(", ".WithSummary(", ".WithDescription(", ".WithTags(", ".RequireAuthorization(", ".ExcludeFromDescription(" };
        calls.Select(call => result.Source.IndexOf(call, StringComparison.Ordinal)).Should().BeInAscendingOrder();
    }

    [TestMethod]
    [DataRow("RequireAuthorization = true")]
    [DataRow("AllowAnonymous = true")]
    [DataRow("Name = null, Summary = null, Description = null, AuthorizationPolicy = null, RequireAuthorization = false, ExcludeFromDescription = false")]
    public void OptionalAuthorizationModesCompile(string options) => Run(
        $"internal static class H {{ [GenerateEndpoint(\"/\", \"GET\", {options})] public static string Read() => \"ok\"; }}").AssertCompiles();

    [TestMethod]
    [DataRow("/orders", "/ORDERS/")]
    [DataRow("/orders/{id}", "/orders/{other}")]
    [DataRow("/orders/{id:int}", "/orders/{other:int}")]
    [DataRow("/files/{*path}", "/files/{**other}")]
    public void DuplicateOrEquivalentRoutesRejectEveryParticipant(string first, string second)
    {
        var result = Run($"internal static class H {{ [GenerateEndpoint(\"{first}\", \"GET\")] public static string A() => \"a\"; [GenerateEndpoint(\"{second}\", \"get\")] public static string B() => \"b\"; }}");
        result.Diagnostics.Should().HaveCount(2).And.OnlyContain(d => d.Id == "IFX2002" && d.AdditionalLocations.Count == 1);
        result.Source.Should().NotContain("global::H.A").And.NotContain("global::H.B");
    }

    [TestMethod]
    public void DifferentVerbsShareRouteButDuplicateNamesFail()
    {
        Run("internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static string A() => \"a\"; [GenerateEndpoint(\"/\", \"POST\")] public static string B() => \"b\"; }").AssertCompiles();
        var result = Run("internal static class H { [GenerateEndpoint(\"/a\", \"GET\", Name=\"Same\")] public static string A() => \"a\"; [GenerateEndpoint(\"/b\", \"GET\", Name=\"Same\")] public static string B() => \"b\"; }");
        result.Diagnostics.Should().HaveCount(2).And.OnlyContain(d => d.Id == "IFX2003");
    }

    [TestMethod]
    public void EmptyAndMissingHostCasesAreExplicit()
    {
        Run("internal class H { }").AssertCompiles();
        GeneratorHarness.Run(Header + "internal class H { }", new MinimalEndpointGenerator(), hosting: false).Source.Should().BeEmpty();
        var result = GeneratorHarness.Run(Header + "internal class H { [GenerateEndpoint(\"/\", \"GET\")] public static string Read() => \"ok\"; }", new MinimalEndpointGenerator(), hosting: false);
        AssertDiagnostic(result, "IFX2005");
        result.Source.Should().BeEmpty();
    }

    [TestMethod]
    public void RegistryCollisionReportsWithoutEmitting() => AssertDiagnostic(Run(
        "namespace vc.Ifx.Generated { internal static class IfxEndpointRouteBuilderExtensions { } } internal class H { [GenerateEndpoint(\"/\", \"GET\")] public static string Read() => \"ok\"; }"), "IFX2007");

    [TestMethod]
    public void ReorderingInputAndChangingUnrelatedSyntaxKeepsOutputStable()
    {
        const string first = "internal static class A { [GenerateEndpoint(\"/z\", \"GET\")] public static string Read() => \"ok\"; }";
        const string second = "internal static class B { [GenerateEndpoint(\"/a\", \"GET\")] public static string Read() => \"ok\"; }";
        var initial = Run(first + second);
        Run(second + first).Source.Should().Be(initial.Source);
        var compilation = GeneratorHarness.Compilation(Header + first + second).AddSyntaxTrees(CSharpSyntaxTree.ParseText("internal class Unrelated { }", GeneratorHarness.ParseOptions));
        var updated = GeneratorHarness.Run(compilation, initial.Driver);
        updated.Source.Should().Be(initial.Source);
        updated.Run.Results[0].TrackedSteps["EndpointSource"].SelectMany(step => step.Outputs).Should().OnlyContain(output => output.Reason == IncrementalStepRunReason.Cached || output.Reason == IncrementalStepRunReason.Unchanged);
    }

    [TestMethod]
    public void CancellationIsPropagated()
    {
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        Action run = () => GeneratorHarness.Run(Header + "internal class H { }", new MinimalEndpointGenerator(), cancellationToken: cancellation.Token);
        run.Should().Throw<OperationCanceledException>();
    }

    [TestMethod]
    [DataRow("/files/{*path}")]
    [DataRow("/files/{**path}")]
    [DataRow("/orders/{id?}")]
    [DataRow("/orders/{id=1}")]
    [DataRow("/orders/{{literal}}")]
    [DataRow("/orders/{{**literal}}")]
    public void FrameworkRouteFormsAndKeywordIdentifiersCompile(string route) => Run(
        $"internal static class H {{ [GenerateEndpoint(\"{route}\", \"GET\")] public static string @class() => \"ok\"; }}").AssertCompiles();

    [TestMethod]
    [DataRow("[GenerateEndpoint]")]
    [DataRow("[GenerateEndpoint(unknown, \"GET\")]")]
    [DataRow("[GenerateEndpoint(\"/\", \"GET\", Name=unknown)]")]
    [DataRow("[GenerateEndpoint(\"/\", \"GET\", Tags=new[]{unknown})]")]
    [DataRow("[GenerateEndpoint(\"/\", \"GET\"), GenerateEndpoint(\"/\", \"GET\")]")]
    public void CompilerInvalidAttributesDoNotCrashOrDuplicateCompilerErrors(string attribute)
    {
        var result = GeneratorHarness.Run(Header + $"internal static class H {{ {attribute} public static string Read() => \"ok\"; }}",
            new MinimalEndpointGenerator(), allowInputErrors: true);
        result.Diagnostics.Should().BeEmpty();
        result.Source.Should().NotContain("global::H.Read");
    }

    [TestMethod]
    public void MissingUnrelatedAttributeDoesNotCrashValidation()
    {
        var result = GeneratorHarness.Run(Header + "internal static class H { [Missing, GenerateEndpoint(\"/\", \"GET\")] public static string Read() => \"ok\"; }",
            new MinimalEndpointGenerator(), allowInputErrors: true);
        result.Diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    [DataRow("private static")]
    [DataRow("public")]
    public void HostingTypeWithoutUsableMethodIsDiagnosed(string modifiers) => AssertDiagnostic(Run($$"""
        namespace Microsoft.AspNetCore.Builder { public class EndpointRouteBuilderExtensions { {{modifiers}} void MapMethods() { } } }
        internal static class H { [GenerateEndpoint("/", "GET")] public static string Read() => "ok"; }
        """), "IFX2005");

    [TestMethod]
    [DataRow("Name=42")]
    [DataRow("Name=new[]{\"text\"}")]
    [DataRow("Name=typeof(string)")]
    [DataRow("RequireAuthorization=\"yes\"")]
    [DataRow("RequireAuthorization=new[]{true}")]
    [DataRow("Tags=\"text\"")]
    public void IncompatibleMarkerMetadataIsDiagnosedWithoutCrashing(string option)
    {
        var result = GeneratorHarness.Run(Header + $$"""
            namespace vc.Ifx.Generators.Abstractions.Attributes
            {
                public sealed class GenerateEndpointAttribute(string route, string method) : Attribute
                {
                    public object Name { get; set; } = "";
                    public object RequireAuthorization { get; set; } = false;
                    public object Tags { get; set; } = "";
                }
            }
            internal static class H { [GenerateEndpoint("/", "GET", {{option}})] public static string Read() => "ok"; }
            """, new MinimalEndpointGenerator(), includeAttributes: false);
        AssertDiagnostic(result, "IFX2000");
        result.Source.Should().NotContain("global::H.Read");
    }

    [TestMethod]
    public void CustomAwaitableAndDelegateArrayAreRejected()
    {
        AssertDiagnostic(Run("internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static string Read(this string value) => value; }"), "IFX2001");
        AssertDiagnostic(Run("internal class Awaitable { public int GetAwaiter() => 1; } internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static Awaitable Read() => new(); }"), "IFX2001");
        AssertDiagnostic(Run("internal static class H { [GenerateEndpoint(\"/\", \"GET\")] public static Func<int>[] Read() => new Func<int>[0]; }"), "IFX2006");
    }

    private static GeneratorHarness.Result Run(string source) => GeneratorHarness.Run(Header + source, new MinimalEndpointGenerator());
    private static void AssertDiagnostic(GeneratorHarness.Result result, string id)
    {
        result.Diagnostics.Should().Contain(d => d.Id == id && d.Severity == DiagnosticSeverity.Error && d.Location.IsInSource);
    }
}
