namespace Ifx.Primitives;

/// <summary>
/// Base type for classes generated by <c>Ifx.Generators.EnumerationGenerator</c> from
/// <c>[GenerateEnumeration]</c>-annotated enums.
/// </summary>
/// <param name="id">The integer identifier backing the original enum member.</param>
/// <param name="name">The original enum member name.</param>
public abstract class Enumeration(int id, string name)
{
    /// <summary>
    /// Gets the integer identifier backing the original enum member.
    /// </summary>
    public int Id { get; } = id;

    /// <summary>
    /// Gets the original enum member name.
    /// </summary>
    public string Name { get; } = name;

    /// <inheritdoc />
    public override string ToString() => Name;
}
