<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Util.Messaging.Azure.ServiceBus</PackageId>
    <Description>Azure Service Bus messaging implementation for Ifx messaging abstractions.</Description>
    <PackageTags>messaging;azure;servicebus;utilities;ifx</PackageTags>
    <RepositoryUrl>https://github.com/visionarycoder/vc.Ifx</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ifx/Ifx.Messaging.Abstractions/Ifx.Messaging.csproj" />
    <ProjectReference Include="../Util.Messaging.Abstractions/Util.Messaging.csproj" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
