using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using vc.Ifx.Analyzers.Helpers;
using vc.Ifx.Analyzers.Rules.Framework;

namespace VisionaryCoder.Framework.Tests.Roslyn.Analyzers.Legacy;

[TestClass]
public sealed class LegacyExecutionTests
{
    public static IEnumerable<object[]> Rules => typeof(Ifx001Signature).Assembly.GetTypes()
        .Where(type => type.Namespace?.StartsWith("vc.Ifx.Analyzers.Rules.", StringComparison.Ordinal) == true &&
            (type.GetField("Rule") is not null || type == typeof(Ifx001Signature)))
        .OrderBy(type => type.Name, StringComparer.Ordinal)
        .Select(type => new object[] { type.Name });

    private const string Source = """
        class A { private int unused; public int Value {get;set;} public decimal Run(decimal value) { if (value > 0) { value += 1m; } return value; } }
        class B { private void Unused() {} }
        """;

    [TestMethod]
    public void OnlyReviewedAnalyzersAreAutomaticallyDiscoverable()
    {
        string[] exported = typeof(Ifx001Signature).Assembly.GetTypes()
            .Where(type => type.GetCustomAttributes(typeof(DiagnosticAnalyzerAttribute), false).Length != 0)
            .Select(type => type.Name).ToArray();
        CollectionAssert.AreEquivalent(new[] { "Ifx001Signature", "DiagnosticDebtAnalyzer", "MethodNestingAnalyzer" }, exported);
    }

    [TestMethod]
    public void LegacyDescriptorsHaveUniqueIdsAndPublishedRemediationLinks()
    {
        var descriptors = Rules.SelectMany(row => LegacyHarness.Rule((string)row[0]).SupportedDiagnostics).ToArray();
        Assert.AreEqual(descriptors.Length, descriptors.Select(rule => rule.Id).Distinct(StringComparer.Ordinal).Count());
        foreach (var rule in descriptors)
        {
            Assert.IsTrue(rule.IsEnabledByDefault);
            Assert.IsTrue(rule.DefaultSeverity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning or DiagnosticSeverity.Info);
            Assert.IsFalse(string.IsNullOrWhiteSpace(rule.Title.ToString()));
            Assert.IsFalse(string.IsNullOrWhiteSpace(rule.MessageFormat.ToString()));
            Assert.IsFalse(string.IsNullOrWhiteSpace(rule.Category));
            Assert.IsTrue(Uri.TryCreate(rule.HelpLinkUri, UriKind.Absolute, out var uri));
            Assert.AreEqual("https", uri!.Scheme);
            StringAssert.Contains(uri.AbsolutePath, "/docs/roslyn/diagnostic-catalog.md");
            Assert.IsFalse(rule.Id.StartsWith("CA", StringComparison.Ordinal) || rule.Id.StartsWith("CS", StringComparison.Ordinal));
        }
    }

    [TestMethod]
    [DynamicData(nameof(Rules))]
    public async Task RuleInstanceHasNoCrossCompilationState(string rule)
    {
        var analyzer = LegacyHarness.Rule(rule);
        foreach (string assembly in new[] { "Manager.Local.Service", "Engine.Local.Service", "Access.Local.Contract", "Ifx.Local" })
        {
            var sequential = await AnalyzerHarness.RunAsync(Source, analyzer, concurrent: false, assemblyName: assembly);
            var parallel = await Task.WhenAll(Enumerable.Range(0, 2).Select(index => AnalyzerHarness.RunAsync(Source, analyzer, assemblyName: assembly)));
            foreach (var result in parallel)
                CollectionAssert.AreEqual(sequential.Select(d => d.ToString()).ToArray(), result.Select(d => d.ToString()).ToArray(), rule);
            Assert.AreEqual(0, (await AnalyzerHarness.RunAsync("public interface I {}", analyzer, assemblyName: assembly)).Length, rule);
        }
    }

    [TestMethod]
    [DynamicData(nameof(Rules))]
    public async Task RulesHonorSuppressionAndGeneratedExclusion(string rule)
    {
        var analyzer = LegacyHarness.Rule(rule);
        foreach (string assembly in new[] { "Manager.Local.Service", "Engine.Local.Service", "Access.Local.Contract" })
        {
            Assert.AreEqual(0, (await AnalyzerHarness.RunAsync(Source, analyzer, assemblyName: assembly, severity: ReportDiagnostic.Suppress)).Length, rule);
            Assert.AreEqual(0, (await AnalyzerHarness.RunAsync(Source, analyzer, assemblyName: assembly, path: "Policy.g.cs")).Length, rule);
            Assert.AreEqual(0, (await AnalyzerHarness.RunAsync("// <auto-generated/>\n" + Source, analyzer, assemblyName: assembly)).Length, rule);
        }
    }

    [TestMethod]
    [DynamicData(nameof(Rules))]
    public async Task CancellationDoesNotPoisonReuse(string rule)
    {
        var analyzer = LegacyHarness.Rule(rule);
        using CancellationTokenSource cancellation = new();
        cancellation.Cancel();
        await Assert.ThrowsAsync<OperationCanceledException>(() => AnalyzerHarness.RunAsync(Source, analyzer, cancellationToken: cancellation.Token));
        var result = await AnalyzerHarness.RunAsync(Source, analyzer);
        Assert.IsTrue(result.All(diagnostic => diagnostic.Id != "AD0001"));
    }

    [TestMethod]
    [DynamicData(nameof(Rules))]
    public async Task BrokenSourceDoesNotCrash(string rule)
    {
        const string source = "[Missing] class C<T> : Unknown { [Missing] public missing P {get;set;} public void () { unknown.Call(); } class Nested {} }";
        foreach (string assembly in new[] { "Manager.Local.Service", "Engine.Local.Service", "Access.Local.Contract", "Ifx.Local" })
            await AnalyzerHarness.RunAsync(source, LegacyHarness.Rule(rule), assemblyName: assembly, allowCompilerErrors: true);
    }

    [TestMethod]
    public async Task DependencyEnumerationCancelsBeforeAndDuringTraversal()
    {
        var compilation = CSharpCompilation.Create("Ifx.Local", [CSharpSyntaxTree.ParseText("interface I { int A {get;} string B {get;} } class C {}")], AnalyzerHarness.References);
        var type = compilation.GetTypeByMetadataName("I")!;
        Assert.AreEqual(2, TypeDependencies.Enumerate(type, default).Count());
        using CancellationTokenSource cancellation = new();
        using var enumerator = TypeDependencies.Enumerate(type, cancellation.Token).GetEnumerator();
        Assert.IsTrue(enumerator.MoveNext());
        cancellation.Cancel();
        await Assert.ThrowsAsync<OperationCanceledException>(() => Task.Run(() => enumerator.MoveNext()));
        await Assert.ThrowsAsync<OperationCanceledException>(() => Task.Run(() => TypeDependencies.Enumerate(type, cancellation.Token).ToArray()));
        await Assert.ThrowsAsync<OperationCanceledException>(() => Task.Run(() => TypeDependencies.Expand(type, cancellation.Token).ToArray()));
    }
}
