using Microsoft.CodeAnalysis;
using Ifx.Analyzers.Abstractions;
using Ifx.Analyzers.Rules;
using Ifx.Roslyn;

namespace Ifx.Tests.Roslyn.Analyzers;

[TestClass]
public sealed class Ifx1400NoUnderscorePrefixedIdentifierTests
{
    [TestMethod]
    public async Task ReportsPrivateFieldsParametersAndLocalsOnceAtIdentifierLocations()
    {
        const string source = """
            class C
            {
                private int _field;
                internal int _ignored;

                void Run(int _parameter)
                {
                    int _local = _parameter + _field;
                    _field = _local;
                }
            }
            """;

        var diagnostics = await AnalyzerHarness.RunAsync(source, new Ifx1400NoUnderscorePrefixedIdentifier());
        diagnostics.Select(diagnostic => diagnostic.Id).Should().Equal(
            DiagnosticIds.Ifx1400NoUnderscorePrefixedIdentifier,
            DiagnosticIds.Ifx1400NoUnderscorePrefixedIdentifier,
            DiagnosticIds.Ifx1400NoUnderscorePrefixedIdentifier);
        diagnostics.Select(diagnostic => diagnostic.GetMessage()).Should().Equal(
            "'_field' should not use a leading underscore; rename without the underscore prefix",
            "'_parameter' should not use a leading underscore; rename without the underscore prefix",
            "'_local' should not use a leading underscore; rename without the underscore prefix");
        diagnostics.Select(diagnostic => source.Substring(diagnostic.Location.SourceSpan.Start, diagnostic.Location.SourceSpan.Length)).Should().Equal("_field", "_parameter", "_local");
        diagnostics.Should().OnlyContain(diagnostic => diagnostic.Severity == DiagnosticSeverity.Warning && diagnostic.Descriptor.Category == DiagnosticCategories.Naming);
        diagnostics.Should().OnlyContain(diagnostic => diagnostic.Descriptor.HelpLinkUri.EndsWith("#ifx1400", StringComparison.Ordinal));
    }

    [TestMethod]
    public async Task ReportsForUsingAndFixedLocals()
    {
        const string source = """
            unsafe class C
            {
                void Run()
                {
                    for (int _index = 0; _index < 1; _index++)
                    {
                    }

                    int[] buffer = new int[1];
                    using var _resource = new Disposable();
                    fixed (int* _pointer = buffer)
                    {
                        *_pointer = 1;
                    }
                }
            }

            sealed class Disposable : System.IDisposable
            {
                public void Dispose()
                {
                }
            }
            """;

        var diagnostics = await AnalyzerHarness.RunAsync(source, new Ifx1400NoUnderscorePrefixedIdentifier());

        diagnostics.Select(diagnostic => source.Substring(diagnostic.Location.SourceSpan.Start, diagnostic.Location.SourceSpan.Length))
            .Should().Equal("_index", "_resource", "_pointer");
    }

    [TestMethod]
    public async Task HiddenFieldLocationsDoNotReportDiagnostics()
    {
        const string source = """
            #line hidden
            class C
            {
                private int _field;
            }
            #line default
            """;

        var diagnostics = await AnalyzerHarness.RunAsync(source, new Ifx1400NoUnderscorePrefixedIdentifier());

        diagnostics.Should().BeEmpty();
    }

    [TestMethod]
    public async Task DoesNotFlagBareUnderscoreOrCompliantNames()
    {
        const string source = """
            class FieldCase
            {
                private int _;
                private int value;

                void Run(int value)
                {
                    int local = value;
                }
            }

            class ParameterCase
            {
                void Run(int _, int value)
                {
                    int local = value;
                    _ = local;
                }
            }

            class LocalCase
            {
                void Run(int value)
                {
                    int local = value;
                    int _ = local;
                    _ = local + value;
                }
            }
            """;

        (await AnalyzerHarness.RunAsync(source, new Ifx1400NoUnderscorePrefixedIdentifier())).Should().BeEmpty();
    }

    [TestMethod]
    [DataRow("Policy.g.cs", "")]
    [DataRow("Policy.generated.cs", "")]
    [DataRow("Policy.cs", "// <auto-generated/>\n")]
    public async Task GeneratedCodeIsExcluded(string path, string header)
    {
        string source = header + """
            class C
            {
                private int _field;

                void Run(int _parameter)
                {
                    int _local = _parameter + _field;
                }
            }
            """;

        (await AnalyzerHarness.RunAsync(source, new Ifx1400NoUnderscorePrefixedIdentifier(), path: path)).Should().BeEmpty();
    }

    [TestMethod]
    public async Task HonorsPreCanceledAnalysis()
    {
        using CancellationTokenSource cancellation = new();
        cancellation.Cancel();
        await Assert.ThrowsAsync<OperationCanceledException>(() =>
            AnalyzerHarness.RunAsync("class C { private int _field; }", new Ifx1400NoUnderscorePrefixedIdentifier(),
                cancellationToken: cancellation.Token));
    }
}
