using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace vc.Ifx.Roslyn.Reporting;

internal static class SourceMetrics
{
    internal static void Analyze(SourceEvidence source, List<SourceFact> facts, List<MethodMetric> metrics,
        List<string> issues, CancellationToken cancellationToken)
    {
        string path = source.Path.Replace('\\', '/');
        if (path.StartsWith('/') || path.Contains(':') || path.Split('/').Contains(".."))
            throw new ArgumentException("Source paths must be repository relative.");
        string? exclusion = null;
        if (path.Split('/').Any(segment => segment is "obj" or "bin") ||
            path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
            source.Text.TrimStart().StartsWith("// <auto-generated", StringComparison.Ordinal))
            exclusion = "GeneratedFile";
        facts.Add(new(path, ReportEngine.Hash(source.Text), exclusion));
        if (exclusion is not null) return;

        SyntaxTree tree = CSharpSyntaxTree.ParseText(source.Text,
            new CSharpParseOptions(LanguageVersion.CSharp14, preprocessorSymbols: source.Symbols),
            cancellationToken: cancellationToken);
        if (tree.GetDiagnostics(cancellationToken).Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            issues.Add($"Invalid source syntax: {path}");
            return;
        }
        PortableExecutableReference generatedReference = MetadataReference.CreateFromFile(typeof(GeneratedCodeAttribute).Assembly.Location);
        CSharpCompilation compilation = CSharpCompilation.Create("SourceMetrics", [tree],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
             generatedReference]);
        INamedTypeSymbol? generatedAttribute = ((IAssemblySymbol)compilation.GetAssemblyOrModuleSymbol(generatedReference)!).GetTypeByMetadataName("System.CodeDom.Compiler.GeneratedCodeAttribute");
        SemanticModel semantic = compilation.GetSemanticModel(tree);
        foreach (MethodDeclarationSyntax method in tree.GetRoot(cancellationToken).DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            cancellationToken.ThrowIfCancellationRequested();
            int start = tree.GetLineSpan(method.Identifier.Span, cancellationToken).StartLinePosition.Line + 1;
            ISymbol? symbol = semantic.GetDeclaredSymbol(method, cancellationToken);
            bool generated = false;
            for (ISymbol? current = symbol; current is not null; current = current.ContainingType)
                generated |= current.GetAttributes().Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, generatedAttribute));
            if (generated)
            {
                facts.Add(new($"{path}:{start}", ReportEngine.Hash(method.ToFullString()), "GeneratedCodeAttribute"));
                continue;
            }
            SyntaxNode? body = (SyntaxNode?)method.Body ?? method.ExpressionBody;
            if (body is null)
            {
                metrics.Add(new(path, start, method.Identifier.ValueText, null, null, null, method.ParameterList.Parameters.Count, "Unknown"));
                continue;
            }
            int decisions = 1;
            int nesting = 0;
            Stack<(SyntaxNode Node, int Depth)> pending = new();
            pending.Push((body, 0));
            while (pending.TryPop(out var item))
            {
                cancellationToken.ThrowIfCancellationRequested();
                SyntaxNode node = item.Node;
                if (node is LocalFunctionStatementSyntax or AnonymousFunctionExpressionSyntax) continue;
                if (node is IfStatementSyntax or ForStatementSyntax or CommonForEachStatementSyntax or WhileStatementSyntax
                    or DoStatementSyntax or CatchClauseSyntax or CaseSwitchLabelSyntax or CasePatternSwitchLabelSyntax
                    or ConditionalExpressionSyntax || node is SwitchExpressionArmSyntax { Pattern: not DiscardPatternSyntax } ||
                    node.IsKind(SyntaxKind.LogicalAndExpression) || node.IsKind(SyntaxKind.LogicalOrExpression) || node.IsKind(SyntaxKind.CoalesceExpression))
                    decisions++;
                int depth = item.Depth;
                if (node is IfStatementSyntax or SwitchStatementSyntax or ForStatementSyntax or CommonForEachStatementSyntax
                    or WhileStatementSyntax or DoStatementSyntax or TryStatementSyntax)
                    depth++;
                nesting = Math.Max(nesting, depth);
                foreach (SyntaxNode child in node.ChildNodes()) pending.Push((child, depth));
            }
            FileLinePositionSpan span = tree.GetLineSpan(body.Span, cancellationToken);
            metrics.Add(new(path, start, method.Identifier.ValueText, decisions, nesting,
                span.EndLinePosition.Line - span.StartLinePosition.Line + 1, method.ParameterList.Parameters.Count,
                nesting > 4 ? "Review" : "Measured"));
        }
    }
}
