using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace vc.Ifx.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class InterceptorsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = GeneratorConstants.GenerateInterceptorsAttributeAbstractionsFullName;
    private const string ServiceRequestFullName = GeneratorConstants.ServiceRequestFullName;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeFullName,
                (node, _) => node is ClassDeclarationSyntax,
                BuildRequest)
            .Where(request => request != null);

        context.RegisterSourceOutput(candidates, (ctx, request) => Emit(ctx, request!));
    }

    private static GenerationRequest? BuildRequest(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var targetType = (INamedTypeSymbol)context.TargetSymbol;
        var attribute = context.Attributes[0];
        var activitySourceName = ReadConstructorString(attribute, 0);

        if (string.IsNullOrWhiteSpace(activitySourceName))
        {
            activitySourceName = targetType.ToDisplayString();
        }

        var interceptorSuffix = ReadNamedString(attribute, "InterceptorSuffix");
        if (string.IsNullOrWhiteSpace(interceptorSuffix))
        {
            interceptorSuffix = ReadNamedString(attribute, "DecoratorSuffix");
        }

        if (string.IsNullOrWhiteSpace(interceptorSuffix))
        {
            interceptorSuffix = "OpenTelemetryInterceptor";
        }

        var interfaces = ReadServiceTypes(attribute)
            .Where(symbol => symbol.TypeKind == TypeKind.Interface)
            .GroupBy(symbol => symbol.ToDisplayString(), StringComparer.Ordinal)
            .Select(group => group.First())
            .ToImmutableArray();

        if (interfaces.Length == 0)
        {
            return null;
        }

        return new GenerationRequest(
            targetType.ContainingNamespace.IsGlobalNamespace ? string.Empty : targetType.ContainingNamespace.ToDisplayString(),
            targetType.Name,
            activitySourceName!,
            interceptorSuffix!,
            interfaces);
    }

    private static string? ReadConstructorString(AttributeData attribute, int index)
    {
        if (attribute.ConstructorArguments.Length <= index)
        {
            return null;
        }

        return attribute.ConstructorArguments[index].Value as string;
    }

    private static string? ReadNamedString(AttributeData attribute, string name)
    {
        foreach (var named in attribute.NamedArguments)
        {
            if (named.Key == name)
            {
                return named.Value.Value as string;
            }
        }

        return null;
    }

    private static IEnumerable<INamedTypeSymbol> ReadServiceTypes(AttributeData attribute)
    {
        if (attribute.ConstructorArguments.Length < 2)
        {
            yield break;
        }

        var typesArgument = attribute.ConstructorArguments[1];

        if (typesArgument.Kind != TypedConstantKind.Array || typesArgument.IsNull)
        {
            yield break;
        }

        foreach (var value in typesArgument.Values)
        {
            if (value.Value is INamedTypeSymbol typeSymbol)
            {
                yield return typeSymbol;
            }
        }
    }

    private static void Emit(SourceProductionContext context, GenerationRequest request)
    {
        var source = GenerateSource(request);
        var hintName = request.TargetNamespace + "." + request.TargetTypeName + ".Interceptors.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(GenerationRequest request)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Diagnostics;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        builder.AppendLine("using Microsoft.Extensions.Logging;");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(request.TargetNamespace))
        {
            builder.Append("namespace ");
            builder.Append(request.TargetNamespace);
            builder.AppendLine();
            builder.AppendLine("{");
        }

        var indent = string.IsNullOrWhiteSpace(request.TargetNamespace) ? string.Empty : "    ";

        builder.Append(indent);
        builder.Append("internal static class ");
        builder.Append(request.TargetTypeName);
        builder.AppendLine("InterceptorsRegistration");
        builder.Append(indent);
        builder.AppendLine("{");

        builder.Append(indent);
        builder.AppendLine("    public static IServiceCollection AddInterceptors(this IServiceCollection services)");
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.AppendLine("        if (services == null)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            throw new ArgumentNullException(nameof(services));");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(indent);
        builder.Append("        services.TryAddSingleton(new ActivitySource(");
        builder.Append(ToLiteral(request.ActivitySourceName));
        builder.AppendLine("));");

        foreach (var contract in request.Contracts)
        {
            var contractType = contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var interceptorType = "global::" + (string.IsNullOrWhiteSpace(request.TargetNamespace) ? string.Empty : request.TargetNamespace + ".") + GetInterceptorName(contract, request.InterceptorSuffix);

            builder.Append(indent);
            builder.Append("        Intercept(services, typeof(");
            builder.Append(contractType);
            builder.Append("), typeof(");
            builder.Append(interceptorType);
            builder.AppendLine("));");
        }

        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("        return services;");
        builder.Append(indent);
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append(indent);
        builder.AppendLine("    private static void Intercept(IServiceCollection services, Type serviceType, Type interceptorType)");
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.AppendLine("        for (var index = services.Count - 1; index >= 0; index--)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            var descriptor = services[index];");
        builder.Append(indent);
        builder.AppendLine("            if (descriptor.ServiceType != serviceType)");
        builder.Append(indent);
        builder.AppendLine("            {");
        builder.Append(indent);
        builder.AppendLine("                continue;");
        builder.Append(indent);
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("            services.RemoveAt(index);");
        builder.Append(indent);
        builder.AppendLine("            services.Insert(index, ServiceDescriptor.Describe(");
        builder.Append(indent);
        builder.AppendLine("                serviceType,");
        builder.Append(indent);
        builder.AppendLine("                provider =>");
        builder.Append(indent);
        builder.AppendLine("                {");
        builder.Append(indent);
        builder.AppendLine("                    var inner = CreateService(provider, descriptor);");
        builder.Append(indent);
        builder.AppendLine("                    return ActivatorUtilities.CreateInstance(provider, interceptorType, inner);");
        builder.Append(indent);
        builder.AppendLine("                },");
        builder.Append(indent);
        builder.AppendLine("                descriptor.Lifetime));");
        builder.Append(indent);
        builder.AppendLine("            return;");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.Append(indent);
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append(indent);
        builder.AppendLine("    private static object CreateService(IServiceProvider provider, ServiceDescriptor descriptor)");
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.AppendLine("        if (descriptor.ImplementationInstance != null)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            return descriptor.ImplementationInstance;");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("        if (descriptor.ImplementationFactory != null)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            return descriptor.ImplementationFactory(provider);");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("        if (descriptor.ImplementationType != null)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            return ActivatorUtilities.GetServiceOrCreateInstance(provider, descriptor.ImplementationType);");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("        throw new InvalidOperationException(\"Unable to resolve service descriptor implementation.\");");
        builder.Append(indent);
        builder.AppendLine("    }");

        builder.Append(indent);
        builder.AppendLine("}");
        builder.AppendLine();

        foreach (var contract in request.Contracts)
        {
            EmitInterceptor(builder, indent, request, contract);
        }

        if (!string.IsNullOrWhiteSpace(request.TargetNamespace))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitInterceptor(StringBuilder builder, string indent, GenerationRequest request, INamedTypeSymbol contract)
    {
        var interceptorName = GetInterceptorName(contract, request.InterceptorSuffix);
        var contractType = contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        builder.Append(indent);
        builder.AppendLine("/// <summary>");
        builder.Append(indent);
        builder.AppendLine("/// Interceptor that wraps and instruments a service interface with observability.");
        builder.Append(indent);
        builder.AppendLine("/// ");
        builder.Append(indent);
        builder.AppendLine("/// This interceptor implements the same interface as the wrapped service and delegates all calls to it.");
        builder.Append(indent);
        builder.AppendLine("/// It intercepts each method invocation to add cross-cutting concerns:");
        builder.Append(indent);
        builder.AppendLine("/// - Creates an OpenTelemetry Activity with operation name and metadata tags");
        builder.Append(indent);
        builder.AppendLine("/// - Records correlation ID and message ID from ServiceMessage parameters");
        builder.Append(indent);
        builder.AppendLine("/// - Sets activity status (Ok/Error) based on method outcome");
        builder.Append(indent);
        builder.AppendLine("/// - Logs operation details including exceptions");
        builder.Append(indent);
        builder.AppendLine("/// - Ensures ConfigureAwait(false) on async operations");
        builder.Append(indent);
        builder.AppendLine("/// </summary>");
        builder.Append(indent);
        builder.Append("internal sealed class ");
        builder.Append(interceptorName);
        builder.Append(" : ");
        builder.Append(contractType);
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("{");

        builder.Append(indent);
        builder.AppendLine("    /// <summary>The wrapped service instance that receives all method calls after instrumentation.</summary>");
        builder.Append(indent);
        builder.Append("    private readonly ");
        builder.Append(contractType);
        builder.AppendLine(" innerService;");
        builder.Append(indent);
        builder.AppendLine("    /// <summary>ActivitySource used to create and manage OpenTelemetry traces for this interceptor.</summary>");
        builder.Append(indent);
        builder.AppendLine("    private readonly ActivitySource activitySource;");
        builder.Append(indent);
        builder.Append("    /// <summary>Logger used to record structured telemetry and exception details.");
        builder.AppendLine("</summary>");
        builder.Append(indent);
        builder.Append("    private readonly ILogger<");
        builder.Append(interceptorName);
        builder.AppendLine("> logger;");
        builder.AppendLine();

        builder.Append(indent);
        builder.AppendLine("    /// <summary>");
        builder.Append(indent);
        builder.AppendLine("    /// Initializes a new instance of the interceptor.");
        builder.Append(indent);
        builder.AppendLine("    /// </summary>");
        builder.Append(indent);
        builder.AppendLine("    /// <param name=\"inner\">The wrapped service instance that implements the actual business logic.</param>");
        builder.Append(indent);
        builder.AppendLine("    /// <param name=\"activitySource\">OpenTelemetry ActivitySource for creating tracing activities.</param>");
        builder.Append(indent);
        builder.AppendLine("    /// <param name=\"logger\">Logger instance for recording operation telemetry and errors.</param>");
        builder.Append(indent);
        builder.Append("    public ");
        builder.Append(interceptorName);
        builder.Append("(");
        builder.Append(contractType);
        builder.Append(" inner, ActivitySource activitySource, ILogger<");
        builder.Append(interceptorName);
        builder.AppendLine("> logger)");
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.AppendLine("        innerService = inner ?? throw new ArgumentNullException(nameof(inner));");
        builder.Append(indent);
        builder.AppendLine("        this.activitySource = activitySource ?? throw new ArgumentNullException(nameof(activitySource));");
        builder.Append(indent);
        builder.AppendLine("        this.logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        builder.Append(indent);
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var property in CollectProperties(contract))
        {
            EmitProperty(builder, indent, property, contract.GetMembers(property.Name).Any(member => member.Kind != SymbolKind.Property));
            builder.AppendLine();
        }

        foreach (var eventSymbol in CollectEvents(contract))
        {
            EmitEvent(builder, indent, eventSymbol);
            builder.AppendLine();
        }

        foreach (var method in CollectMethods(contract))
        {
            EmitMethod(builder, indent, contract, method);
            builder.AppendLine();
        }

        builder.Append(indent);
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static IEnumerable<IMethodSymbol> CollectMethods(INamedTypeSymbol contract)
    {
        var signatures = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in contract.GetMembers().OfType<IMethodSymbol>())
        {
            if (symbol.MethodKind != MethodKind.Ordinary)
            {
                continue;
            }

            var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (signatures.Add(key))
            {
                yield return symbol;
            }
        }

        foreach (var inherited in contract.AllInterfaces)
        {
            foreach (var symbol in inherited.GetMembers().OfType<IMethodSymbol>())
            {
                if (symbol.MethodKind != MethodKind.Ordinary)
                {
                    continue;
                }

                var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (signatures.Add(key))
                {
                    yield return symbol;
                }
            }
        }
    }

    private static IEnumerable<IPropertySymbol> CollectProperties(INamedTypeSymbol contract)
    {
        var signatures = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in contract.GetMembers().OfType<IPropertySymbol>())
        {
            var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (signatures.Add(key))
            {
                yield return symbol;
            }
        }

        foreach (var inherited in contract.AllInterfaces)
        {
            foreach (var symbol in inherited.GetMembers().OfType<IPropertySymbol>())
            {
                var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (signatures.Add(key))
                {
                    yield return symbol;
                }
            }
        }
    }

    private static IEnumerable<IEventSymbol> CollectEvents(INamedTypeSymbol contract)
    {
        var signatures = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in contract.GetMembers().OfType<IEventSymbol>())
        {
            var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (signatures.Add(key))
            {
                yield return symbol;
            }
        }

        foreach (var inherited in contract.AllInterfaces)
        {
            foreach (var symbol in inherited.GetMembers().OfType<IEventSymbol>())
            {
                var key = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (signatures.Add(key))
                {
                    yield return symbol;
                }
            }
        }
    }

    private static void EmitProperty(StringBuilder builder, string indent, IPropertySymbol property, bool explicitImplementation)
    {
        var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var propertyName = EscapeIdentifier(property.Name);
        var declaringType = property.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (property.IsIndexer)
        {
            builder.Append(indent);
            builder.Append("    public ");
            builder.Append(propertyType);
            builder.Append(" this[");
            builder.Append(BuildParameterDeclarationList(property.Parameters));
            builder.AppendLine("]");
            builder.Append(indent);
            builder.AppendLine("    {");

            if (property.GetMethod != null)
            {
                builder.Append(indent);
                builder.Append("        get => innerService[");
                builder.Append(BuildParameterInvocationList(property.Parameters));
                builder.AppendLine("]; ");
            }

            if (property.SetMethod != null)
            {
                builder.Append(indent);
                builder.Append("        set => innerService[");
                builder.Append(BuildParameterInvocationList(property.Parameters));
                builder.AppendLine("] = value;");
            }

            builder.Append(indent);
            builder.AppendLine("    }");
            return;
        }

        builder.Append(indent);
        builder.Append(explicitImplementation ? "    " : "    public ");
        builder.Append(propertyType);
        builder.Append(' ');
        if (explicitImplementation) { builder.Append(declaringType).Append('.'); }
        builder.Append(propertyName);
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("    {");

        if (property.GetMethod != null)
        {
            builder.Append(indent);
            builder.Append("        get => ((").Append(declaringType).Append(")innerService).");
            builder.Append(propertyName);
            builder.AppendLine(";");
        }

        if (property.SetMethod != null)
        {
            builder.Append(indent);
            builder.Append("        set => ((").Append(declaringType).Append(")innerService).");
            builder.Append(propertyName);
            builder.AppendLine(" = value;");
        }

        builder.Append(indent);
        builder.AppendLine("    }");
    }

    private static void EmitEvent(StringBuilder builder, string indent, IEventSymbol eventSymbol)
    {
        var eventType = eventSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var eventName = EscapeIdentifier(eventSymbol.Name);

        builder.Append(indent);
        builder.Append("    public event ");
        builder.Append(eventType);
        builder.Append(' ');
        builder.Append(eventName);
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.Append("        add => innerService.");
        builder.Append(eventName);
        builder.AppendLine(" += value;");
        builder.Append(indent);
        builder.Append("        remove => innerService.");
        builder.Append(eventName);
        builder.AppendLine(" -= value;");
        builder.Append(indent);
        builder.AppendLine("    }");
    }

    private static void EmitMethod(StringBuilder builder, string indent, INamedTypeSymbol contract, IMethodSymbol method)
    {
        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = EscapeIdentifier(method.Name);
        var parameters = BuildParameterDeclarationList(method.Parameters);
        var callArguments = BuildParameterInvocationList(method.Parameters);
        var typeParameterList = BuildTypeParameterList(method);
        var constraints = BuildConstraints(method);

        var isTask = IsTask(method.ReturnType, out var taskTypeArgument);
        var isValueTask = IsValueTask(method.ReturnType, out var valueTaskTypeArgument);
        var isAsync = isTask || isValueTask;

        builder.Append(indent);
        builder.Append("    public ");
        if (isAsync)
        {
            builder.Append("async ");
        }

        builder.Append(returnType);
        builder.Append(' ');
        builder.Append(methodName);
        builder.Append(typeParameterList);
        builder.Append('(');
        builder.Append(parameters);
        builder.Append(')');

        if (!string.IsNullOrWhiteSpace(constraints))
        {
            builder.AppendLine();
            builder.Append(indent);
            builder.Append("    ");
            builder.Append(constraints);
        }

        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("    {");
        builder.Append(indent);
        builder.Append("        using var activity = activitySource.StartActivity(");
        builder.Append(ToLiteral(contract.Name + "." + method.Name));
        builder.AppendLine(", ActivityKind.Internal);");
        builder.Append(indent);
        builder.AppendLine("        activity?.SetTag(\"component.layer\", \"Boundary\");");
        builder.Append(indent);
        builder.Append("        activity?.SetTag(\"component.contract\", ");
        builder.Append(ToLiteral(contract.ToDisplayString()));
        builder.AppendLine(");");
        builder.Append(indent);
        builder.Append("        activity?.SetTag(\"operation.name\", ");
        builder.Append(ToLiteral(method.Name));
        builder.AppendLine(");");

        var serviceRequestParameter = FindServiceRequestParameter(method.Parameters);
        if (serviceRequestParameter != null)
        {
            var parameterName = EscapeIdentifier(serviceRequestParameter.Name);

            builder.Append(indent);
            builder.Append("        if (");
            builder.Append(parameterName);
            builder.AppendLine(" != null)");
            builder.Append(indent);
            builder.AppendLine("        {");
            builder.Append(indent);
            builder.Append("            activity?.SetTag(\"message.correlation_id\", ");
            builder.Append(parameterName);
            builder.AppendLine(".CorrelationId);");
            builder.Append(indent);
            builder.Append("            activity?.SetTag(\"message.id\", ");
            builder.Append(parameterName);
            builder.AppendLine(".MessageId);");
            builder.Append(indent);
            builder.Append("            logger.LogInformation(\"OpenTelemetry boundary metadata for {Contract}.{Operation}. CorrelationId={CorrelationId}, MessageId={MessageId}\", activity?.GetTagItem(\"component.contract\"), activity?.GetTagItem(\"operation.name\"), ");
            builder.Append(parameterName);
            builder.Append(".CorrelationId, ");
            builder.Append(parameterName);
            builder.AppendLine(".MessageId);");
            builder.Append(indent);
            builder.AppendLine("        }");
        }

        builder.Append(indent);
        builder.AppendLine("        try");
        builder.Append(indent);
        builder.AppendLine("        {");

        if (method.ReturnsVoid)
        {
            builder.Append(indent);
            builder.Append("            innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(");");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return;");
        }
        else if (isTask && taskTypeArgument == null)
        {
            builder.Append(indent);
            builder.Append("            await innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(").ConfigureAwait(false);");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return;");
        }
        else if (isTask && taskTypeArgument != null)
        {
            builder.Append(indent);
            builder.Append("            var result = await innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(").ConfigureAwait(false);");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return result;");
        }
        else if (isValueTask && valueTaskTypeArgument == null)
        {
            builder.Append(indent);
            builder.Append("            await innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(").ConfigureAwait(false);");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return;");
        }
        else if (isValueTask && valueTaskTypeArgument != null)
        {
            builder.Append(indent);
            builder.Append("            var result = await innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(").ConfigureAwait(false);");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return result;");
        }
        else
        {
            builder.Append(indent);
            builder.Append("            var result = innerService.");
            builder.Append(methodName);
            builder.Append(typeParameterList);
            builder.Append('(');
            builder.Append(callArguments);
            builder.AppendLine(");");
            builder.Append(indent);
            builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
            builder.Append(indent);
            builder.AppendLine("            return result;");
        }

        builder.Append(indent);
        builder.AppendLine("        }");
        builder.Append(indent);
        builder.AppendLine("        catch (Exception ex)");
        builder.Append(indent);
        builder.AppendLine("        {");
        builder.Append(indent);
        builder.AppendLine("            activity?.SetStatus(ActivityStatusCode.Error, ex.Message);");
        builder.Append(indent);
        // RecordException() is not available in System.Diagnostics.Activity
        builder.Append(indent);
        builder.AppendLine("            logger.LogError(ex, \"OpenTelemetry boundary call failed for {Contract}.{Operation}\", activity?.GetTagItem(\"component.contract\"), activity?.GetTagItem(\"operation.name\"));");
        builder.Append(indent);
        builder.AppendLine("            throw;");
        builder.Append(indent);
        builder.AppendLine("        }");
        builder.Append(indent);
        builder.AppendLine("    }");
    }

    private static IParameterSymbol? FindServiceRequestParameter(ImmutableArray<IParameterSymbol> parameters)
    {
        foreach (var parameter in parameters)
        {
            if (IsServiceRequestType(parameter.Type))
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool IsServiceRequestType(ITypeSymbol typeSymbol)
    {
        var namedType = typeSymbol as INamedTypeSymbol;
        while (namedType != null)
        {
            if (string.Equals(namedType.ToDisplayString(), ServiceRequestFullName, StringComparison.Ordinal))
            {
                return true;
            }

            namedType = namedType.BaseType;
        }

        return false;
    }

    private static string BuildTypeParameterList(IMethodSymbol method)
    {
        if (method.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        return "<" + string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name)) + ">";
    }

    private static string BuildConstraints(IMethodSymbol method)
    {
        var clauses = new List<string>();

        foreach (var typeParameter in method.TypeParameters)
        {
            var constraints = new List<string>();

            if (typeParameter.HasReferenceTypeConstraint)
            {
                constraints.Add("class");
            }

            if (typeParameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (typeParameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            foreach (var constraintType in typeParameter.ConstraintTypes)
            {
                constraints.Add(constraintType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            if (typeParameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count > 0)
            {
                clauses.Add("where " + typeParameter.Name + " : " + string.Join(", ", constraints));
            }
        }

        return string.Join(" ", clauses);
    }

    private static string BuildParameterDeclarationList(ImmutableArray<IParameterSymbol> parameters)
    {
        return string.Join(", ", parameters.Select(p => BuildParameterDeclaration(p)));
    }

    private static string BuildParameterDeclaration(IParameterSymbol parameter)
    {
        var builder = new StringBuilder();

        if (parameter.IsParams)
        {
            builder.Append("params ");
        }
        else if (parameter.RefKind == RefKind.Ref)
        {
            builder.Append("ref ");
        }
        else if (parameter.RefKind == RefKind.Out)
        {
            builder.Append("out ");
        }
        else if (parameter.RefKind == RefKind.In)
        {
            builder.Append("in ");
        }

        builder.Append(parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        builder.Append(' ');
        builder.Append(EscapeIdentifier(parameter.Name));

        return builder.ToString();
    }

    private static string BuildParameterInvocationList(ImmutableArray<IParameterSymbol> parameters)
    {
        return string.Join(", ", parameters.Select(p => BuildParameterInvocation(p)));
    }

    private static string BuildParameterInvocation(IParameterSymbol parameter)
    {
        var prefix = string.Empty;

        if (parameter.RefKind == RefKind.Ref)
        {
            prefix = "ref ";
        }
        else if (parameter.RefKind == RefKind.Out)
        {
            prefix = "out ";
        }
        else if (parameter.RefKind == RefKind.In)
        {
            prefix = "in ";
        }

        return prefix + EscapeIdentifier(parameter.Name);
    }

    private static bool IsTask(ITypeSymbol typeSymbol, out ITypeSymbol? typeArgument)
    {
        typeArgument = null;

        if (!(typeSymbol is INamedTypeSymbol namedType))
        {
            return false;
        }

        if (namedType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
        {
            return false;
        }

        if (namedType.Name != "Task")
        {
            return false;
        }

        if (namedType.TypeArguments.Length == 1)
        {
            typeArgument = namedType.TypeArguments[0];
        }

        return true;
    }

    private static bool IsValueTask(ITypeSymbol typeSymbol, out ITypeSymbol? typeArgument)
    {
        typeArgument = null;

        if (!(typeSymbol is INamedTypeSymbol namedType))
        {
            return false;
        }

        if (namedType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
        {
            return false;
        }

        if (namedType.Name != "ValueTask")
        {
            return false;
        }

        if (namedType.TypeArguments.Length == 1)
        {
            typeArgument = namedType.TypeArguments[0];
        }

        return true;
    }

    private static string GetInterceptorName(INamedTypeSymbol contract, string suffix)
    {
        var nameBuilder = new StringBuilder(contract.Name.Replace("`", string.Empty));

        if (contract.TypeArguments.Length > 0)
        {
            foreach (var typeArgument in contract.TypeArguments)
            {
                nameBuilder.Append('_');
                nameBuilder.Append(typeArgument.Name.Replace("`", string.Empty));
            }
        }

        nameBuilder.Append(suffix);
        return nameBuilder.ToString();
    }

    private static string EscapeIdentifier(string identifier)
    {
        if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None)
        {
            return "@" + identifier;
        }

        return identifier;
    }

    private static string ToLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private sealed class GenerationRequest
    {
        public GenerationRequest(string targetNamespace, string targetTypeName, string activitySourceName, string interceptorSuffix, ImmutableArray<INamedTypeSymbol> contracts)
        {
            TargetNamespace = targetNamespace;
            TargetTypeName = targetTypeName;
            ActivitySourceName = activitySourceName;
            InterceptorSuffix = interceptorSuffix;
            Contracts = contracts;
        }

        public string TargetNamespace { get; }
        public string TargetTypeName { get; }
        public string ActivitySourceName { get; }
        public string InterceptorSuffix { get; }
        public ImmutableArray<INamedTypeSymbol> Contracts { get; }
    }
}
